engines:
  pep8:
    enabled: true
  shellcheck:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      # Line too long
      MD013:
        enabled: false
      # Trailing punctuation in header
      MD026:
        enabled: false
  csslint:
    enabled: true
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - python
  radon: 
    enabled: true
ratings:
  paths:
    - "**.py"
    - "**.sh"
    - "README.md"
    - "scoreboard/html_static/css/style.css"
    - "scoreboard/html_static/js/dcss-scoreboard.js"
exclude_paths:
  - awesomeplete.min.js
  - awesomeplete.css
  - jquery.timeago.js
  - tether.min.js
