language: python
cache: pip
python:
  - "3.5"
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - pip install yapf pylint
  - pip install -r requirements.txt
script:
  - echo -en 'travis_fold:start:yapf\\r'
  - test/yapf.sh
  - echo -en 'travis_fold:end:yapf\\r'
  - echo -en 'travis_fold:start:pylint\\r'
  - pylint scoreboard
  - echo -en 'travis_fold:end:pylint\\r'
