language: python
cache: pip
python:
  - "3.5"
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - pip install yapf pylint
  - pip install -r requirements.txt
script:
  - echo "syntax..." && echo -en 'travis_fold:start:syntax\\r'
  - make syntax
  - echo "yapf..." && echo -en 'travis_fold:start:yapf\\r'
  - make yapf
  - echo -en 'travis_fold:end:yapf\\r'
  - echo "pylint..." && echo -en 'travis_fold:start:pylint\\r'
  - make pylint
  - echo -en 'travis_fold:end:pylint\\r'
  #- echo "mypy..." && echo -en 'travis_fold:start:mypy\\r'
  #- make mypy
  #- echo -en 'travis_fold:end:mypy\\r'
